// using the try catch and the finally block

console.log("Hello 1 ");
console.log("Hello 1 ");


try{
    console.log("print a = "+a);
    
}catch{
    console.log("This variable does not exists here. Please try again.");
    
}
// this is the finally block of the 
finally{
    console.log("This is the finally block of the code written hare.");
    
}
console.log("Hello 2 ");
console.log("Hello 2 ");